import { FoodItem } from "../types";

export const foodDatabase: FoodItem[] = [
  // Nasi & Karbohidrat
  {
    id: "1",
    name: "Nasi Putih",
    calories: 130,
    protein: 2.7,
    fat: 0.3,
    carbs: 28,
    glycemicIndex: "high",
    servingSize: "1 porsi (100g)",
  },
  {
    id: "2",
    name: "Nasi Merah",
    calories: 110,
    protein: 2.6,
    fat: 0.9,
    carbs: 23,
    glycemicIndex: "low",
    servingSize: "1 porsi (100g)",
  },
  {
    id: "3",
    name: "Roti Gandum",
    calories: 247,
    protein: 13,
    fat: 3.4,
    carbs: 41,
    glycemicIndex: "medium",
    servingSize: "2 lembar",
  },
  {
    id: "4",
    name: "Kentang Rebus",
    calories: 87,
    protein: 2,
    fat: 0.1,
    carbs: 20,
    glycemicIndex: "medium",
    servingSize: "1 buah sedang",
  },
  {
    id: "5",
    name: "Ubi Jalar",
    calories: 86,
    protein: 1.6,
    fat: 0.1,
    carbs: 20,
    glycemicIndex: "low",
    servingSize: "1 buah sedang (100g)",
  },

  // Protein
  {
    id: "6",
    name: "Ayam Dada Panggang",
    calories: 165,
    protein: 31,
    fat: 3.6,
    carbs: 0,
    glycemicIndex: "low",
    servingSize: "1 porsi (100g)",
  },
  {
    id: "7",
    name: "Ikan Salmon",
    calories: 208,
    protein: 20,
    fat: 13,
    carbs: 0,
    glycemicIndex: "low",
    servingSize: "1 porsi (100g)",
  },
  {
    id: "8",
    name: "Telur Rebus",
    calories: 155,
    protein: 13,
    fat: 11,
    carbs: 1.1,
    glycemicIndex: "low",
    servingSize: "2 butir",
  },
  {
    id: "9",
    name: "Tempe",
    calories: 193,
    protein: 20,
    fat: 11,
    carbs: 9,
    glycemicIndex: "low",
    servingSize: "1 porsi (100g)",
  },
  {
    id: "10",
    name: "Tahu",
    calories: 76,
    protein: 8,
    fat: 4.8,
    carbs: 1.9,
    glycemicIndex: "low",
    servingSize: "1 porsi (100g)",
  },

  // Sayuran
  {
    id: "11",
    name: "Brokoli Kukus",
    calories: 55,
    protein: 3.7,
    fat: 0.6,
    carbs: 11,
    glycemicIndex: "low",
    servingSize: "1 mangkuk",
  },
  {
    id: "12",
    name: "Bayam",
    calories: 23,
    protein: 2.9,
    fat: 0.4,
    carbs: 3.6,
    glycemicIndex: "low",
    servingSize: "1 mangkuk",
  },
  {
    id: "13",
    name: "Wortel",
    calories: 41,
    protein: 0.9,
    fat: 0.2,
    carbs: 10,
    glycemicIndex: "medium",
    servingSize: "1 buah sedang",
  },

  // Buah
  {
    id: "14",
    name: "Pisang",
    calories: 89,
    protein: 1.1,
    fat: 0.3,
    carbs: 23,
    glycemicIndex: "medium",
    servingSize: "1 buah sedang",
  },
  {
    id: "15",
    name: "Apel",
    calories: 52,
    protein: 0.3,
    fat: 0.2,
    carbs: 14,
    glycemicIndex: "low",
    servingSize: "1 buah sedang",
  },
  {
    id: "16",
    name: "Alpukat",
    calories: 160,
    protein: 2,
    fat: 15,
    carbs: 9,
    glycemicIndex: "low",
    servingSize: "1/2 buah",
  },

  // Minuman & Lainnya
  {
    id: "17",
    name: "Susu Rendah Lemak",
    calories: 42,
    protein: 3.4,
    fat: 1,
    carbs: 5,
    glycemicIndex: "low",
    servingSize: "1 gelas (200ml)",
  },
  {
    id: "18",
    name: "Yogurt Plain",
    calories: 59,
    protein: 10,
    fat: 0.4,
    carbs: 3.6,
    glycemicIndex: "low",
    servingSize: "1 cup (100g)",
  },
  {
    id: "19",
    name: "Kacang Almond",
    calories: 579,
    protein: 21,
    fat: 50,
    carbs: 22,
    glycemicIndex: "low",
    servingSize: "1 genggam (100g)",
  },
  {
    id: "20",
    name: "Oatmeal",
    calories: 389,
    protein: 17,
    fat: 7,
    carbs: 66,
    glycemicIndex: "low",
    servingSize: "1 mangkuk (100g)",
  },

  // Makanan tinggi gula (untuk warning)
  {
    id: "21",
    name: "Nasi Goreng",
    calories: 333,
    protein: 8,
    fat: 12,
    carbs: 48,
    glycemicIndex: "high",
    servingSize: "1 porsi",
  },
  {
    id: "22",
    name: "Mi Instan",
    calories: 371,
    protein: 9,
    fat: 14,
    carbs: 53,
    glycemicIndex: "high",
    servingSize: "1 bungkus",
  },
  {
    id: "23",
    name: "Minuman Bersoda",
    calories: 140,
    protein: 0,
    fat: 0,
    carbs: 39,
    glycemicIndex: "high",
    servingSize: "1 kaleng (330ml)",
  },
  {
    id: "24",
    name: "Kue Donat",
    calories: 452,
    protein: 5,
    fat: 25,
    carbs: 51,
    glycemicIndex: "high",
    servingSize: "1 buah",
  },
];

export const foodAlternatives: Record<string, string[]> = {
  "1": ["2", "5"], // Nasi Putih -> Nasi Merah, Ubi Jalar
  "21": ["2", "20"], // Nasi Goreng -> Nasi Merah, Oatmeal
  "22": ["3", "6"], // Mi Instan -> Roti Gandum, Ayam
  "23": ["17"], // Minuman Bersoda -> Susu
  "24": ["14", "15"], // Kue Donat -> Pisang, Apel
};

export const exerciseTypes = [
  { name: "Jalan Kaki", caloriesPerMinute: 3.5 },
  { name: "Jogging", caloriesPerMinute: 7 },
  { name: "Lari", caloriesPerMinute: 10 },
  { name: "Bersepeda", caloriesPerMinute: 6 },
  { name: "Berenang", caloriesPerMinute: 8 },
  { name: "Yoga", caloriesPerMinute: 3 },
  { name: "Angkat Beban", caloriesPerMinute: 5 },
  { name: "Aerobik", caloriesPerMinute: 6.5 },
];
